const google_pass=require('../passport')
const express=require('express')
const userRouter=express();
userRouter.set('view engine','ejs')
const mid_user=require('../middleware/userAuth')
userRouter.set('views','views/users')
userRouter.use(express.static('public/users'))
const loadHome=require('../controller/User/loadHome')
const loadSI=require('../controller/User/loadSI')
const loadRG=require('../controller/User/loadRG')
const loadOTP=require('../controller/User/loadOTP')
const loadResentotp=require('../controller/User/loadResentotp')
const reset_password=require('../controller/User/reset_password')
const otp=require('../controller/User/otp')
const repassword=require('../controller/User/repassword')
const loadRepassword=require('../controller/User/loadRepassword')
const logOut=require('../controller/User/logOut')
const render_Product=require('../controller/User/render_Product')
const productView=require('../controller/User/productView')
const render_women=require('../controller/User/render_women')
const render_men=require('../controller/User/render_men')
const homesearch=require('../controller/User/homesearch')
const personalInfo=require('../controller/User/personalInfo')
const EditAddress=require('../controller/User/EditAddress')
const AddorUpdateAddress=require('../controller/User/AddorUpdateAddress')
const EditAddressrender=require('../controller/User/EditAddressrender')
const updateAddress=require('../controller/User/updateAddress')
const deleteAddress=require('../controller/User/deleteAddress')
const cartRender=require('../controller/User/cartRender')
const addToCart=require('../controller/User/addToCart')
const cartdynamic=require('../controller/User/cartdynamic')
const removeCartProduct=require('../controller/User/removeCartProduct')
const checkoutRender=require('../controller/User/checkoutRender')
const edituser=require('../controller/User/edituser')
const userPassword=require('../controller/User/userPassword')
const order=require('../controller/User/order')
const removeproductorder=require('../controller/User/removeproductorder')
const productDetailsInOrder=require('../controller/User/productDetailsInOrder')
const sortProduct=require('../controller/User/sortProduct')
const filteredProduct=require('../controller/User/filteredProduct')






userRouter.get('/homePage',loadHome) 
userRouter.get('/homesearch',homesearch)
userRouter.post('/loadEP',loadSI)
userRouter.post('/loadRG',loadRG)
userRouter.post('/loadOTP',loadOTP)
userRouter.get('/otp',otp)
userRouter.get('/resentOTP',loadResentotp)
userRouter.post('/reset_password',reset_password)
userRouter.post('/loadOTP/repassword',repassword)
userRouter.post('/loadrepassword',loadRepassword)
userRouter.get('/auth/google',google_pass.googleAuth);
userRouter.get("/auth/google/callback",google_pass.googleCallback,google_pass.setupSession);
userRouter.get('/product',render_Product)
userRouter.get('/men',render_men)
userRouter.get('/women',render_women)
userRouter.get('/productView',productView)
userRouter.get('/personalInfo',personalInfo)
userRouter.post('/edituser',edituser)
userRouter.post('/userPassword',userPassword)
userRouter.get('/EditAddress',EditAddress)
userRouter.post('/addorupdateaddress',AddorUpdateAddress)
userRouter.get('/editAddressrender',EditAddressrender)
userRouter.get('/cart/add',addToCart)
userRouter.get('/cart',cartRender)
userRouter.post('/cartdynamic',cartdynamic)
userRouter.post('/removeCartProduct',removeCartProduct)
userRouter.get('/checkout',checkoutRender)
userRouter.post('/order',order)
userRouter.post('/removeproductorder',removeproductorder)
userRouter.post('/productDetailsInOrder',productDetailsInOrder)
userRouter.post('/updateaddress',updateAddress)
userRouter.delete('/deleteAddress',deleteAddress)
userRouter.get("/logout",logOut)
userRouter.post('/sortProduct',sortProduct)
userRouter.post('/filteredProduct',filteredProduct)


module.exports={userRouter}